import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import javax.swing.border.EmptyBorder;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JMenuItem;


public class CrawlerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CrawlerGUI
     */
    public Crawler crawl=new Crawler();
    
    public CrawlerGUI() {
        initComponents();
        this.setTitle("Static Link Finder");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        URLin = new javax.swing.JTextField();
        URLLabel = new javax.swing.JLabel();
        BaseIn = new javax.swing.JTextField();
        BaseLabel = new javax.swing.JLabel();
        depthIn = new javax.swing.JTextField();
        DepthLabel = new javax.swing.JLabel();
        runButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        staticLinkTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        URLin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLinActionPerformed(evt);
            }
        });

        URLLabel.setText("URL");

        BaseIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseInActionPerformed(evt);
            }
        });

        BaseLabel.setText("Base URL");

        depthIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depthInActionPerformed(evt);
            }
        });

        DepthLabel.setText("Depth");

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        staticLinkTextArea.setColumns(20);
        staticLinkTextArea.setRows(5);
        jScrollPane1.setViewportView(staticLinkTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(URLin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(URLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BaseIn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DepthLabel)
                                    .addComponent(depthIn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(runButton)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(URLLabel)
                    .addComponent(BaseLabel)
                    .addComponent(DepthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(URLin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BaseIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depthIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(runButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
        
        menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        
        mnNewMenu = new JMenu("Help ");
        menuBar.add(mnNewMenu);
        
        mntmHelp = new JMenuItem("Help (Not implemented yet contact mlemke@liveperson.com)");
        mnNewMenu.add(mntmHelp);
    }// </editor-fold>                        

    private void URLinActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void BaseInActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void depthInActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       


    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) { 
    	
    	//Warns user of wait times
        staticLinkTextArea.append("Building Site Map (this can take a while depending on depth) \n");
        
        
        //sends the base urls and requested depth
        crawl.CrawlerInit(URLin.getText(), BaseIn.getText(),Integer.parseInt(depthIn.getText()));
        //crawl.CrawlerInit("http://www.asquithnurseries.co.uk/", "asquithnurseries.co.uk", 0);
        
        //launches crawler as a thread searches results upon completion
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
        	   @Override
        	   protected Void doInBackground() throws Exception {
        		crawl.runCrawler();
        		
        		staticLinkTextArea.append("Building Complete, Searching for Static Links \n");
				return null;
        	    
        	   }


        	   protected void done() { 
        		   
        		  
        		   new Thread(new Runnable() {
        		        public void run() {
        		        	 crawl.runListURL();
        		        }
        		    }).start();
        		   
        		   
        		   
        		   SwingWorker<Void, Void> worker2 = new SwingWorker<Void, Void>() {
                	   @Override
                	   protected Void doInBackground() throws Exception {
                		   String current="Starting search \n";
                		   while(!crawl.flag().equals("done")){
                			   System.out.println("in the while and flag is "+crawl.flag()+ " and current is "+current+"\n");
                			   if(!current.equals(crawl.flag())){
                				current=crawl.flag();
              		        	staticLinkTextArea.append(crawl.flag()+"\n");
                				System.out.println(crawl.flag());
                			   }
                    		}
        				return null;
                	    
                	   }


                	   protected void done() { 
                		   staticLinkTextArea.append("These links have static buttons. \n");
                    	  	for(int i=0;i<crawl.StaticUrls.size();i++){
                    		  staticLinkTextArea.append((i+1) +". "+crawl.StaticUrls.get(i)+" \n");
                     	  }
                	   }
                	   
                	   
                	  };
                	  
                	  worker2.execute();
        		   
        		   
        		   
        		   //for the update
       		   /*     while(!crawl.flag().equals("done")){
       		        	System.out.println(crawl.flag());
       		        	staticLinkTextArea.append(crawl.flag());
             		}*/
    			   
    			   
        		   /*staticLinkTextArea.append("These links have static buttons. \n");
             	  	for(int i=0;i<crawl.StaticUrls.size();i++){
             		  staticLinkTextArea.append((i+1) +". "+crawl.StaticUrls.get(i)+" \n");*/
        	   }
        	   
        	   
        	  };
        	  
        	  worker.execute();
        	  
        	 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrawlerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrawlerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrawlerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrawlerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrawlerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField BaseIn;
    private javax.swing.JLabel BaseLabel;
    private javax.swing.JLabel DepthLabel;
    private javax.swing.JLabel URLLabel;
    private javax.swing.JTextField URLin;
    private javax.swing.JTextField depthIn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton runButton;
    private javax.swing.JTextArea staticLinkTextArea;
    private JMenuBar menuBar;
    private JMenu mnNewMenu;
    private JMenuItem mntmHelp;
    // End of variables declaration                   
}
